---
- name: include os specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: install memcached
  yum:
    name: memcached
    state: present

- name: configure memcached
  template:
    src: etc+sysconfig+memcached
    dest: /etc/sysconfig/{{ item.key }}
  with_dict: "{{ memcached_list }}"

- name: create init script for each memcached
  template:
    src: "{{ memcached_init_src }}"
    dest: "{{ memcached_init_dst }}"
    mode: 0755
  with_dict: "{{ memcached_list }}"

- name: start all memcached service
  service:
    name: "{{ item.key }}"
    state: started
    enabled: true
  with_dict: "{{ memcached_list }}"
